name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install ecs-cli
        uses: ./
        with:
          version: "v1.18.0"
      - run: ecs-cli --version
  test-shell:
    runs-on: ubuntu-latest
    steps:
      - run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/marocchino/setup-ecs-cli/from-shell/entrypoint.sh)"
      - run: ecs-cli --version
