name: test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install ecs-cli
        uses: ./
        with:
          version: "v1.16.0"
      - run: ecs-cli --version
